### ISSUE TITLE
Log output show success even when a test fails

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago-ost-plugin#56]
testlib.LogCollectorPlugin should be fixed. It should show `ERROR` message when a test fails.

```bash
17:12:52 [basic-suit] @ Run test: 007_sd_reattach.py: 
17:12:52 [basic-suit] nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
17:12:52 [basic-suit]   # deactivate_storage_domain: 
17:12:52 [basic-suit]     * Collect artifacts: 
17:13:19 [basic-suit]     * Collect artifacts: Success (in 0:00:23)
17:13:19 [basic-suit]   # deactivate_storage_domain: Success (in 0:00:24)
17:13:19 [basic-suit]   # Results located at /dev/shm/ost/deployment-basic-suite-4.2/default/007_sd_reattach.py.junit.xml
17:13:19 [basic-suit] @ Run test: 007_sd_reattach.py: Success (in 0:00:24)
17:13:19 [basic-suit] Error occured, aborting
17:13:19 [basic-suit] Traceback (most recent call last):
17:13:19 [basic-suit]   File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 362, in do_run
17:13:19 [basic-suit]     self.cli_plugins[args.ovirtverb].do_run(args)
17:13:19 [basic-suit]   File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
17:13:19 [basic-suit]     self._do_run(**vars(args))
17:13:19 [basic-suit]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 505, in wrapper
17:13:19 [basic-suit]     return func(*args, **kwargs)
17:13:19 [basic-suit]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 516, in wrapper
17:13:19 [basic-suit]     return func(*args, prefix=prefix, **kwargs)
17:13:19 [basic-suit]   File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 99, in do_ovirt_runtest
17:13:19 [basic-suit]     raise RuntimeError('Some tests failed')
17:13:19 [basic-suit] RuntimeError: Some tests failed
```

**Comment by galitf** [comment]
When doing the change to capture the fail

the output will change to 
17:12:52 [basic-suit] @ Run test: 007_sd_reattach.py: 
17:12:52 [basic-suit] nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
17:12:52 [basic-suit]   # deactivate_storage_domain: 
17:12:52 [basic-suit]     * Collect artifacts: 
17:13:19 [basic-suit]     * Collect artifacts: Success (in 0:00:23)
17:13:19 [basic-suit]   # deactivate_storage_domain: Success (in 0:00:24)
17:13:19 [basic-suit]   # Results located at /dev/shm/ost/deployment-basic-suite-4.2/default/007_sd_reattach.py.junit.xml
17:13:19 [basic-suit] @ Run test: 007_sd_reattach.py: ERROR (in 0:00:24)

Is that what you meant to happen?
